//! End to end over the real pipeline: a checked-in export is imported,
//! analyzed, composed against and then deleted.
//!
//! Nothing here is mocked except the model provider, which is deterministic on
//! purpose so the assertions are about Mimic's behaviour and not a model's.
//!
//! This test also writes the contract fixtures under `fixtures/contracts/`,
//! which `packages/contracts/test/contracts.test.ts` parses with zod. A change
//! to a Rust read model that is not made in the zod schema fails there, and a
//! change to the shapes that is deliberate is regenerated by running this test
//! with `MIMIC_REGEN_FIXTURES=1`.

use std::path::{Path, PathBuf};

use mimic_core::db::{Db, IdentifierKind, NewSource};
use mimic_core::generation::{feedback, Adjustment, ComposeRequest};
use mimic_core::providers::mock::MockProvider;
use mimic_core::{import, voice};
use serde_json::Value;

fn repo_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("..").join("..")
}

fn fixture(name: &str) -> PathBuf {
    repo_root().join("fixtures").join(name)
}

/// Compare a read model with its checked-in fixture, or rewrite the fixture
/// when explicitly asked to.
fn check_fixture(name: &str, value: &Value) {
    let path = fixture(&format!("contracts/{name}"));
    let pretty = format!("{}\n", serde_json::to_string_pretty(value).unwrap());
    if std::env::var("MIMIC_REGEN_FIXTURES").is_ok() {
        std::fs::create_dir_all(path.parent().unwrap()).unwrap();
        std::fs::write(&path, &pretty).unwrap();
        return;
    }
    let existing = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("missing fixture {}: {e}. Run with MIMIC_REGEN_FIXTURES=1", path.display()));
    let existing: Value = serde_json::from_str(&existing).unwrap();
    // Shape, not values: timestamps and ids differ per run.
    assert_eq!(shape(&existing), shape(value), "the shape of {name} changed; regenerate the fixture if intended");
}

/// A structural skeleton: keys and value kinds, with array element shapes
/// unified, so a fixture comparison is stable across runs.
fn shape(v: &Value) -> Value {
    match v {
        Value::Object(map) => Value::Object(map.iter().map(|(k, v)| (k.clone(), shape(v))).collect()),
        Value::Array(items) => match items.first() {
            Some(first) => Value::Array(vec![shape(first)]),
            None => Value::Array(vec![]),
        },
        Value::String(_) => Value::String("string".into()),
        Value::Number(_) => Value::String("number".into()),
        Value::Bool(_) => Value::String("boolean".into()),
        Value::Null => Value::String("null".into()),
    }
}

fn setup() -> (Db, String) {
    let db = Db::open_in_memory().unwrap();
    db.set_user_identity("C").unwrap();
    db.add_user_identifier(IdentifierKind::Email, "c@example.com").unwrap();
    // The same person, reachable two ways: the SMS thread uses a phone number.
    db.add_user_identifier(IdentifierKind::Phone, "+1 (555) 010-1111").unwrap();
    let source = db
        .create_source(&NewSource {
            connector: "mimic_json".into(),
            name: "Sample export".into(),
            channel: "chat".into(),
            location: Some(fixture("import/sample_export.json").to_string_lossy().into()),
            config: Value::Null,
        })
        .unwrap();
    (db, source.id)
}

fn run_import(db: &Db, source_id: &str) -> import::ImportSummary {
    import::import_source(db, source_id, &mut |_, _| {}, &|| false).unwrap()
}

#[test]
fn import_attributes_messages_across_channels_and_identifier_kinds() {
    let (db, source_id) = setup();
    let summary = run_import(&db, &source_id);

    assert_eq!(summary.conversations, 3);
    assert_eq!(summary.inserted, 46);
    assert_eq!(summary.from_self, 22, "20 emails and 2 texts are the user's");
    assert_eq!(summary.unattributed, 1, "the author with no address stays unknown");
    assert_eq!(summary.participants_created, 2, "Ada and Bob — and the ghost is nobody");

    // The phone number matched despite being formatted three different ways.
    assert_eq!(db.count_self_messages(Some("sms"), None).unwrap(), 2);
    assert_eq!(db.count_self_messages(Some("chat"), None).unwrap(), 20);
    // Bob is one person, not three.
    let bob = db.list_participants(10).unwrap().into_iter().find(|p| p.participant.display_name == "Bob").unwrap();
    assert_eq!(bob.participant.identifiers.len(), 1);
    assert_eq!(bob.message_count, 5);
}

#[test]
fn analysis_produces_measurable_layers_and_honest_gaps() {
    let (db, source_id) = setup();
    run_import(&db, &source_id);
    let summary = voice::analyze(&db, &mut |_, _| {}).unwrap();

    assert_eq!(summary.messages_considered, 22);
    let overview = voice::overview(&db).unwrap();
    assert!(!overview.stale);
    assert_eq!(overview.own_messages, 22);
    assert_eq!(overview.messages_until_measurable, 0);

    let global = overview.profiles.iter().find(|p| p.layer == "global").unwrap();
    assert!(global.measurable, "22 of the user's messages is enough for a global profile");
    assert!(global.metrics.lowercase_start_rate.unwrap() > 0.8, "this user writes in lowercase");
    assert!(global.metrics.terminal_period_rate.unwrap() < 0.2, "and without full stops");
    assert!(global.metrics.top_phrases.iter().any(|(p, _)| p == "let me know"));

    // The SMS channel has two messages: reported, not guessed at.
    let sms = overview.profiles.iter().find(|p| p.scope_key == "sms").unwrap();
    assert!(!sms.measurable);
    assert_eq!(sms.sample_size, 2);
    assert_eq!(sms.metrics.emoji_rate, None, "two messages produce no rates at all");

    check_fixture("voice_overview.json", &serde_json::to_value(&overview).unwrap());
}

#[test]
fn compose_uses_the_relationship_it_has_and_says_when_it_has_none() {
    let (db, source_id) = setup();
    run_import(&db, &source_id);
    voice::analyze(&db, &mut |_, _| {}).unwrap();
    let ada = db
        .list_participants(10)
        .unwrap()
        .into_iter()
        .find(|p| p.participant.display_name == "Ada Lovelace")
        .unwrap()
        .participant
        .id;
    db.set_participant_relationship(&ada, Some("colleague")).unwrap();

    let request = ComposeRequest {
        participant_id: Some(ada.clone()),
        channel: "chat".into(),
        incoming_message: Some("can you send the deck again?".into()),
        intent: Some("yes, tomorrow morning".into()),
        ..Default::default()
    };
    let ctx = mimic_core::generation::build_context(&db, &request).unwrap();
    assert!(ctx.evidence.iter().any(|e| e.contains("messages to this person")), "{:?}", ctx.evidence);
    assert!(!ctx.examples.is_empty());
    assert!(ctx.examples.iter().any(|e| e.reason.starts_with("similar wording")), "{:?}", ctx.examples);
    check_fixture("generation_context.json", &serde_json::to_value(&ctx).unwrap());

    let provider = MockProvider::answering("yeah, sending it tomorrow morning");
    let draft = mimic_core::generation::compose(&db, &provider, &request).unwrap();
    let prompt = provider.last_request().unwrap();
    assert!(prompt.system.contains("colleague"));
    assert!(prompt.system.contains("lowercase"), "the measured habit reached the prompt: {}", prompt.system);
    assert!(prompt.messages.last().unwrap().content.contains("yes, tomorrow morning"));
    check_fixture("draft.json", &serde_json::to_value(&draft).unwrap());

    // Someone with no history gets the global voice and is told so.
    let stranger = ComposeRequest { participant_id: None, channel: "email".into(), ..request.clone() };
    let ctx = mimic_core::generation::build_context(&db, &stranger).unwrap();
    assert!(ctx.effective.measurable, "the global profile still applies");
    assert!(ctx.evidence.iter().any(|e| e.contains("messages overall")));
}

#[test]
fn an_adjustment_changes_the_prompt_and_the_draft_is_recorded_either_way() {
    let (db, source_id) = setup();
    run_import(&db, &source_id);
    voice::analyze(&db, &mut |_, _| {}).unwrap();
    let base = ComposeRequest {
        channel: "chat".into(),
        incoming_message: Some("thoughts on the forecast?".into()),
        intent: Some("agree, will revise".into()),
        ..Default::default()
    };
    let provider = MockProvider::default();
    mimic_core::generation::compose(&db, &provider, &base).unwrap();
    let plain = provider.last_request().unwrap();
    mimic_core::generation::compose(
        &db,
        &provider,
        &ComposeRequest { adjustment: Some(Adjustment::MoreProfessional), ..base.clone() },
    )
    .unwrap();
    let adjusted = provider.last_request().unwrap();

    assert_ne!(plain.system, adjusted.system);
    assert!(adjusted.system.contains("more formally"));
    assert_eq!(db.recent_drafts(10).unwrap().len(), 2);
}

#[test]
fn the_learning_loop_records_what_the_user_actually_sent() {
    let (db, source_id) = setup();
    run_import(&db, &source_id);
    voice::analyze(&db, &mut |_, _| {}).unwrap();
    let request = ComposeRequest {
        channel: "chat".into(),
        incoming_message: Some("can you review the appendix?".into()),
        intent: Some("yes, this afternoon".into()),
        ..Default::default()
    };
    let provider = MockProvider::answering("Hi Ada,\n\nYes, I will review the appendix this afternoon.\n\nThanks, C");
    let draft = mimic_core::generation::compose(&db, &provider, &request).unwrap();

    // The user cuts it to how they actually write.
    let sent = "sure, i'll take a look this afternoon";
    db.resolve_draft(&draft.id, "sent_edited", Some(sent)).unwrap();
    let diff = feedback::diff_draft(&draft.generated_text, sent);
    assert!(diff.greeting_removed && diff.sign_off_removed);
    assert_eq!(diff.length_direction, "shorter");
    db.add_draft_feedback(&draft.id, "edit", feedback::EDIT_WEIGHT, &serde_json::to_value(&diff).unwrap(), None)
        .unwrap();
    db.add_draft_feedback(
        &draft.id,
        "preference",
        feedback::PREFERENCE_WEIGHT,
        &serde_json::json!({"greeting": "none"}),
        Some("I never greet Ada"),
    )
    .unwrap();

    let feedback_rows = db.draft_feedback(&draft.id).unwrap();
    assert_eq!(feedback_rows.len(), 2);
    assert_eq!(feedback_rows[0].kind, "preference", "the stated preference outranks the inferred edit");
    assert_eq!(db.pending_feedback_count().unwrap(), 2);

    let outcomes = db.measured_draft_outcomes().unwrap();
    assert_eq!(outcomes.sent_edited, 1);
    assert_eq!(outcomes.unedited_rate, Some(0.0), "one edited send is a measured 0%, not an absence of data");
}

#[test]
fn deleting_a_person_removes_them_from_everything_the_pipeline_built() {
    let (db, source_id) = setup();
    run_import(&db, &source_id);
    voice::analyze(&db, &mut |_, _| {}).unwrap();
    let ada = db
        .list_participants(10)
        .unwrap()
        .into_iter()
        .find(|p| p.participant.display_name == "Ada Lovelace")
        .unwrap()
        .participant
        .id;

    let before = db.count_self_messages(None, None).unwrap();
    let preview = db.preview_participant_deletion(&ada).unwrap();
    assert_eq!(db.count_self_messages(None, None).unwrap(), before, "previewing writes nothing");
    check_fixture("deletion_report.json", &serde_json::to_value(&preview).unwrap());

    let report = db.delete_participant(&ada).unwrap();
    assert_eq!(report, preview);
    assert_eq!(report.messages, 40);
    assert_eq!(report.own_messages, 20);
    assert!(report.voice_profiles >= 1);

    // Nothing of hers survives, anywhere.
    assert!(db.get_participant(&ada).unwrap().is_none());
    assert!(db.representative_examples(mimic_core::db::VoiceLayer::Relationship, &ada, 10).unwrap().is_empty());
    assert_eq!(own_messages_mentioning(&db, "quarterly deck"), 0, "her words are gone, not orphaned");

    // And the aggregates that included her are invalid until recomputed.
    let global = db
        .get_voice_profile(mimic_core::db::VoiceLayer::Global, "", mimic_core::version::ANALYSIS_VERSION)
        .unwrap()
        .unwrap();
    assert!(global.stale);
    voice::analyze(&db, &mut |_, _| {}).unwrap();
    let after = voice::overview(&db).unwrap();
    assert_eq!(after.own_messages, 2, "only the SMS thread is left");
    let global = after.profiles.iter().find(|p| p.layer == "global").unwrap();
    assert!(!global.measurable, "two messages cannot describe a style, and it says so");
}

#[test]
fn re_running_the_whole_pipeline_changes_nothing() {
    let (db, source_id) = setup();
    run_import(&db, &source_id);
    voice::analyze(&db, &mut |_, _| {}).unwrap();
    let first = serde_json::to_value(voice::overview(&db).unwrap()).unwrap();

    let second_import = run_import(&db, &source_id);
    assert_eq!(second_import.inserted, 0);
    assert_eq!(second_import.duplicates, 46);
    voice::analyze(&db, &mut |_, _| {}).unwrap();
    let second = serde_json::to_value(voice::overview(&db).unwrap()).unwrap();

    assert_eq!(strip_times(&first), strip_times(&second), "an idempotent import produces an identical profile");
}

/// Drop the fields that legitimately differ between two runs.
fn strip_times(v: &Value) -> Value {
    match v {
        Value::Object(map) => Value::Object(
            map.iter()
                .filter(|(k, _)| !matches!(k.as_str(), "lastAnalyzedAt" | "computedAt"))
                .map(|(k, v)| (k.clone(), strip_times(v)))
                .collect(),
        ),
        Value::Array(items) => Value::Array(items.iter().map(strip_times).collect()),
        other => other.clone(),
    }
}

/// How many of the user's own messages still mention a phrase. Used to prove
/// a deletion really removed the text rather than orphaning the rows.
fn own_messages_mentioning(db: &Db, needle: &str) -> usize {
    let mut found = 0;
    for channel in ["chat", "sms", "email", "forum", "other"] {
        for m in db.page_self_messages(Some(channel), None, None, 10_000).unwrap() {
            if m.body.contains(needle) {
                found += 1;
            }
        }
    }
    found
}

#[test]
fn the_import_fixture_is_where_the_tests_say_it_is() {
    let path = fixture("import/sample_export.json");
    assert!(path.is_file(), "{}", path.display());
    assert!(
        Path::new(&repo_root().join("fixtures/contracts")).exists() || std::env::var("MIMIC_REGEN_FIXTURES").is_ok()
    );
}

/// The home screen over a real import: what is waiting, what Mimic prepared
/// for it, and the fixture the zod suite parses.
#[test]
fn the_dashboard_shows_what_is_waiting_and_what_was_prepared_for_it() {
    let (db, source_id) = setup();
    run_import(&db, &source_id);
    voice::analyze(&db, &mut |_, _| {}).unwrap();

    let before = mimic_core::dashboard::dashboard(&db, 25, false, false).unwrap();
    assert!(before.messages > 0);
    assert!(before.last_import_at.is_some(), "an import has happened, so the screen may say so");
    assert!(!before.auto_draft, "assisted drafting is off unless it was turned on");
    assert!(
        before.awaiting.iter().all(|t| t.draft.is_none()),
        "nothing is drafted before assisted drafting runs or the user asks"
    );
    let waiting = before.awaiting.len();
    assert!(waiting > 0, "the sample export ends on messages from other people");

    // Turning it on is what allows a model to see an incoming message the user
    // did not hand over itself.
    db.set_setting(mimic_core::assist::SETTING, &true).unwrap();
    let provider = MockProvider::answering("sure, sending it now");
    let summary = mimic_core::assist::draft_waiting_threads(&db, &provider, 25, &mut |_, _| {}, &|| false).unwrap();
    assert!(!summary.disabled);
    assert_eq!(summary.drafted, summary.considered);
    assert!(summary.drafted > 0);

    let after = mimic_core::dashboard::dashboard(&db, 25, true, false).unwrap();
    assert_eq!(after.awaiting.len(), waiting, "drafting a reply does not answer the thread");
    let drafted = after.awaiting.iter().filter(|t| t.draft.is_some()).count();
    assert_eq!(drafted, summary.drafted, "every prepared draft is attached to its thread");
    assert_eq!(after.pending_drafts.len(), summary.drafted);
    assert!(after.pending_drafts.iter().all(|d| d.outcome.is_none()), "prepared, never pre-approved");
    assert_eq!(after.outcomes.unedited_rate, None, "nothing has been resolved, so the rate is unmeasured");
    assert_eq!(after.left_out, mimic_core::db::LeftOut::default(), "an export of people's messages has no bulk mail");
    assert!(!after.showing_left_out && after.left_out_threads.is_empty());

    // Mail a machine sent is not someone waiting. It is counted, and it is
    // there when asked for; it is not loaded when it is not.
    let news = db.upsert_conversation(&source_id, "news-1", "chat", Some("This week")).unwrap();
    db.insert_messages(&[mimic_core::db::NewMessage {
        conversation_id: news.clone(),
        source_id: source_id.clone(),
        participant_id: None,
        external_id: "news-1-a".into(),
        direction: "other".into(),
        channel: "chat".into(),
        sent_at: Some("2026-01-01T08:00:00Z".into()),
        sequence_index: 0,
        body: "Twenty percent off everything this week.".into(),
        reply_to_external_id: None,
        metadata: serde_json::json!({ "automated": "newsletter" }),
    }])
    .unwrap();
    db.refresh_conversation_stats(&news).unwrap();
    let with_news = mimic_core::dashboard::dashboard(&db, 25, true, false).unwrap();
    assert_eq!(with_news.awaiting.len(), waiting, "a newsletter is not someone waiting");
    assert_eq!(with_news.left_out.automated, 1);
    assert!(!with_news.showing_left_out && with_news.left_out_threads.is_empty());
    let again = mimic_core::assist::draft_waiting_threads(&db, &provider, 25, &mut |_, _| {}, &|| false).unwrap();
    assert_eq!(again.considered, 0, "and nothing is drafted for it");

    // Taking a person's thread off the list moves it to what was left out,
    // with its draft, because saying a thread needs no reply says nothing
    // about the draft.
    let off = after.awaiting[0].conversation_id.clone();
    let seen = after.awaiting[0].last_message_id.clone();
    assert!(db.mark_thread(&off, &seen, Some(mimic_core::db::ThreadMark::NoReplyNeeded)).unwrap());
    let marked = mimic_core::dashboard::dashboard(&db, 25, true, true).unwrap();
    assert_eq!(marked.awaiting.len(), waiting - 1);
    assert_eq!(marked.awaiting_total, waiting as i64 - 1);
    assert_eq!(marked.left_out, mimic_core::db::LeftOut { automated: 1, not_needed: 1 });
    let taken = marked.left_out_threads.iter().find(|t| t.conversation_id == off).unwrap();
    assert_eq!(taken.mark, Some(mimic_core::db::ThreadMark::NoReplyNeeded));
    assert!(taken.draft.is_some(), "no draft was resolved by it");

    // Putting it back is exactly that.
    db.mark_thread(&off, &seen, None).unwrap();
    let shown = mimic_core::dashboard::dashboard(&db, 25, true, true).unwrap();
    assert_eq!(shown.awaiting.len(), waiting);
    assert_eq!(shown.left_out_threads.len(), 1);
    assert_eq!(shown.left_out_threads[0].automated.as_deref(), Some("newsletter"));
    assert!(shown.showing_left_out);

    check_fixture("dashboard.json", &serde_json::to_value(&shown).unwrap());

    // Approving one is the ordinary draft resolution: it records what was
    // sent and takes the draft off the screen. It does not send anything.
    let draft = after.pending_drafts[0].clone();
    let resolved = db.resolve_draft(&draft.id, "sent_unedited", Some(&draft.generated_text)).unwrap();
    assert_eq!(resolved.outcome.as_deref(), Some("sent_unedited"));
    let later = mimic_core::dashboard::dashboard(&db, 25, true, false).unwrap();
    assert_eq!(later.pending_drafts.len(), summary.drafted - 1);
    assert_eq!(later.outcomes.resolved, 1);
}

/// Situations over a real import: what the classifier filed, the situation a
/// note is read as, and the fixtures the zod suite parses for both.
#[test]
fn situations_are_filed_from_the_users_own_messages_and_read_from_a_note() {
    let (db, source_id) = setup();
    run_import(&db, &source_id);
    let summary = voice::analyze(&db, &mut |_, _| {}).unwrap();
    assert!(summary.messages_classified > 0, "the sample export has scheduling and thanks in it");

    let situations = mimic_core::situations::overview(&db).unwrap();
    assert_eq!(situations.len(), 6, "the whole vocabulary, including what has nothing filed yet");
    let scheduling = situations.iter().find(|s| s.id == "scheduling").unwrap();
    assert!(scheduling.own_messages >= 1, "\"tuesday works, 2pm suits me\" is setting a time");
    assert!(!scheduling.measurable, "and one or two messages is not a layer anyone should trust");
    check_fixture("situations.json", &serde_json::to_value(&situations).unwrap());

    let request = ComposeRequest {
        channel: "chat".into(),
        incoming_message: Some("can you make the offsite on the 14th?".into()),
        intent: Some("no, can't make it that week".into()),
        ..Default::default()
    };
    let ctx = mimic_core::generation::build_context(&db, &request).unwrap();
    let sit = ctx.situation.as_ref().expect("the note reads like a no");
    assert_eq!(sit.id, "declining");
    assert!(ctx.evidence.iter().any(|e| e.starts_with("Your note reads like saying no")), "{:?}", ctx.evidence);
    check_fixture("generation_context_situation.json", &serde_json::to_value(&ctx).unwrap());
}

/// The loop closed over a real import: three drafts to Ada sent without the
/// greeting Mimic put on them, and the fourth is written without one.
#[test]
fn what_the_user_changes_three_times_the_next_draft_does_by_itself() {
    let (db, source_id) = setup();
    run_import(&db, &source_id);
    voice::analyze(&db, &mut |_, _| {}).unwrap();
    let ada = db
        .list_participants(10)
        .unwrap()
        .into_iter()
        .find(|p| p.participant.display_name == "Ada Lovelace")
        .unwrap()
        .participant
        .id;
    let request = ComposeRequest {
        participant_id: Some(ada.clone()),
        channel: "chat".into(),
        incoming_message: Some("can you send the deck again?".into()),
        intent: Some("yes, tomorrow morning".into()),
        ..Default::default()
    };
    let provider = MockProvider::answering("Hi Ada,\n\nyeah, sending it tomorrow morning");
    for _ in 0..3 {
        let d = mimic_core::generation::compose(&db, &provider, &request).unwrap();
        db.resolve_draft(&d.id, "sent_edited", Some("yeah, sending it tomorrow morning then")).unwrap();
    }
    mimic_core::learning::remember_note(&db, Some(&ada), "keep it to one line").unwrap();

    mimic_core::generation::compose(&db, &provider, &request).unwrap();
    let prompt = provider.last_request().unwrap();
    assert!(prompt.system.contains("- Do not open with a greeting."), "{}", prompt.system);
    assert!(prompt.system.contains("- keep it to one line"));

    let overview = mimic_core::learning::overview(&db).unwrap();
    assert_eq!(overview.drafts_considered, 3);
    assert!(overview.patterns.iter().any(|p| p.holds && p.participant_id.as_deref() == Some(ada.as_str())));
    check_fixture("learning.json", &serde_json::to_value(&overview).unwrap());
}
