//! Whether a message was sent by a machine rather than written to the user by
//! a person.
//!
//! This exists because a connected inbox is mostly not people. Before it, the
//! home screen listed every newsletter, receipt and notification as someone
//! waiting on a reply, and assisted drafting spent its run answering them.
//!
//! It decides from **headers only** — what the sending system declared about
//! the message — and never from the words. The rules are the ones mail
//! systems themselves use to decide whether to auto-reply (RFC 3834) and
//! which the large providers require of bulk senders (RFC 2369 list headers,
//! `List-Unsubscribe`). Precision over recall, like the situation classifier:
//! a newsletter that slips through costs one glance, while a person filed away
//! as a machine is a reply the user never sees. So:
//!
//! * A list message counts only when it also gives nowhere to post. A
//!   discussion list — a team's Google Group, a Mailman list — carries
//!   `List-Post`, and a colleague writing there is a person.
//! * `Precedence` decides almost nothing. `list` is what discussion lists
//!   send; `bulk` is what help desks (Request Tracker) put on replies their
//!   staff write, and what some list software (ezmlm) puts on every post. Only
//!   `junk`, which nobody puts on a person's mail, decides by itself. Bulk
//!   senders are caught anyway: the large providers require
//!   `List-Unsubscribe` of them.
//! * A no-reply address counts only when its local part says so outright —
//!   and not when `Reply-To` names somebody who can be answered, which is how
//!   contact forms and booking services pass on a real person's message.
//!   `info@`, `hello@` and `support@` are read by people and are left alone.
//!
//! The result is a reading, not a fact the user stated, and the screen says it
//! that way. The user's own call on a thread (`thread_marks`) outranks it.

use super::mime::{header, Headers};

/// Why a message looks automated. The string form is stored on the message
/// (`metadata.automated`) and read by the dashboard, so the variants are part
/// of the data model: rename one and the stored value stops meaning anything.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Automated {
    /// A delivery report: a bounce, a delay notice or a read receipt
    /// (`Content-Type: multipart/report`).
    Report,
    /// Sent automatically in answer to something, or generated by a system:
    /// out-of-office replies included (`Auto-Submitted`, a null
    /// `Return-Path`).
    AutoReply,
    /// Marked by its sender as junk (`Precedence: junk`).
    Bulk,
    /// From an address that says not to reply to it.
    NoReplyAddress,
    /// Sent through a list (`List-Id` or `List-Unsubscribe`) with nowhere to
    /// post: a newsletter, or notifications from a service.
    Newsletter,
}

impl Automated {
    pub fn as_str(self) -> &'static str {
        match self {
            Automated::Report => "report",
            Automated::AutoReply => "auto_reply",
            Automated::Bulk => "bulk",
            Automated::NoReplyAddress => "no_reply_address",
            Automated::Newsletter => "newsletter",
        }
    }
}

/// Local parts that say "do not reply" in so many words. Compared after the
/// `+tag` is removed and case is folded.
const NO_REPLY_LOCAL_PARTS: [&str; 12] = [
    "noreply",
    "no-reply",
    "no_reply",
    "no.reply",
    "donotreply",
    "do-not-reply",
    "do_not_reply",
    "dontreply",
    "mailer-daemon",
    "postmaster",
    "bounce",
    "bounces",
];

/// The same words at either end of a longer local part: `noreply-apps@`,
/// `no-reply.billing@`, `comments-noreply@`, `messages-noreply@`.
const NO_REPLY_WORDS: [&str; 5] = ["noreply", "no-reply", "no_reply", "donotreply", "do-not-reply"];

/// The first reason a message looks automated, or `None` for a message that
/// looks like a person wrote it. `from` is the sender's address, if it has one.
pub fn detect(headers: &Headers, from: Option<&str>) -> Option<Automated> {
    let value = |name: &str| header(headers, name).map(|v| v.trim().to_ascii_lowercase());

    if value("content-type").is_some_and(|ct| ct.starts_with("multipart/report")) {
        return Some(Automated::Report);
    }
    // RFC 3834 and its extensions: auto-generated, auto-replied,
    // auto-notified. `no` is a person, and so is `auto-forwarded` — a person's
    // message sent on by a rule is still a person's message.
    if let Some(auto) = value("auto-submitted") {
        let kind = strip_comments(&auto);
        let kind = kind.split(';').next().unwrap_or_default().trim();
        if kind.starts_with("auto-") && kind != "auto-forwarded" {
            return Some(Automated::AutoReply);
        }
    }
    if value("x-autoreply").is_some() || value("x-autorespond").is_some() {
        return Some(Automated::AutoReply);
    }
    // A null return path is how RFC 3834 says automatic replies and bounces
    // should be sent, so that they are never answered in turn. A person's mail
    // always has somewhere to bounce to.
    if value("return-path").is_some_and(|rp| rp.trim() == "<>") {
        return Some(Automated::AutoReply);
    }
    match value("precedence").as_deref().map(strip_comments).as_deref().map(str::trim) {
        Some("junk") => return Some(Automated::Bulk),
        Some("auto_reply") => return Some(Automated::AutoReply),
        _ => {}
    }
    if from.is_some_and(is_no_reply_address) && !answerable_reply_to(value("reply-to").as_deref(), from) {
        return Some(Automated::NoReplyAddress);
    }
    let on_a_list = value("list-unsubscribe").is_some() || value("list-id").is_some();
    if on_a_list && !can_post_to_list(value("list-post").as_deref()) {
        return Some(Automated::Newsletter);
    }
    None
}

/// `List-Post: NO` is RFC 2369's way of saying posting is not allowed; an
/// absent header says nothing either way, and on a list that also offers an
/// unsubscribe link, nothing is what a newsletter says.
fn can_post_to_list(list_post: Option<&str>) -> bool {
    match list_post.map(strip_comments) {
        None => false,
        Some(v) => {
            let v = v.trim();
            !v.is_empty() && !v.eq_ignore_ascii_case("no") && (v.contains("mailto:") || v.contains("http"))
        }
    }
}

/// Whether `Reply-To` names someone who can be answered: not a no-reply
/// address, and not on the sender's own domain — a service that relays
/// replies (`reply+token@service`) is still the service. The price, taken on
/// purpose: an internal system that sends a colleague's message from
/// `noreply@company` with `Reply-To: them@company` reads as automated, and the
/// user puts it back with "It needs a reply".
fn answerable_reply_to(reply_to: Option<&str>, from: Option<&str>) -> bool {
    let Some(raw) = reply_to else { return false };
    let from_domain = from.and_then(|f| f.trim().rsplit_once('@')).map(|(_, d)| d.to_ascii_lowercase());
    raw.split(',').filter_map(address_in).any(|a| {
        let domain = a.rsplit_once('@').map(|(_, d)| d.to_string());
        !is_no_reply_address(&a) && domain != from_domain
    })
}

/// The address in `Name <a@b>` or a bare `a@b`, lowercased.
fn address_in(part: &str) -> Option<String> {
    let part = part.trim();
    let addr = match (part.find('<'), part.rfind('>')) {
        (Some(open), Some(close)) if close > open => &part[open + 1..close],
        _ => part,
    };
    let addr = addr.trim().to_ascii_lowercase();
    addr.contains('@').then_some(addr)
}

/// RFC 5322 comments — `(like this)` — say nothing about the value.
fn strip_comments(v: &str) -> String {
    let mut out = String::with_capacity(v.len());
    let mut depth = 0usize;
    for c in v.chars() {
        match c {
            '(' => depth += 1,
            ')' if depth > 0 => depth -= 1,
            _ if depth == 0 => out.push(c),
            _ => {}
        }
    }
    out
}

fn is_no_reply_address(address: &str) -> bool {
    let Some((local, _domain)) = address.trim().rsplit_once('@') else { return false };
    let local = local.split('+').next().unwrap_or(local).to_ascii_lowercase();
    // The word must stand on its own: `noreply-apps` and `comments-noreply`,
    // not `noreplying` or `snoreply`.
    NO_REPLY_LOCAL_PARTS.contains(&local.as_str())
        || NO_REPLY_WORDS.iter().any(|w| {
            local.strip_prefix(w).is_some_and(|rest| rest.is_empty() || rest.starts_with(['-', '_', '.']))
                || local.strip_suffix(w).is_some_and(|rest| rest.ends_with(['-', '_', '.']))
        })
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::sources::mime::parse_headers;

    fn check(block: &str, from: Option<&str>) -> Option<Automated> {
        detect(&parse_headers(block), from)
    }

    #[test]
    fn a_person_writing_is_left_alone() {
        let h = "From: Ada <ada@example.com>\nTo: me@example.com\nSubject: lunch?\nContent-Type: text/plain";
        assert_eq!(check(h, Some("ada@example.com")), None);
        // Addresses that people read, even when they sound like a department.
        for addr in ["info@shop.example", "support@example.com", "hello@studio.example", "noreen@example.com"] {
            assert_eq!(check(h, Some(addr)), None, "{addr} is not a no-reply address");
        }
    }

    #[test]
    fn a_newsletter_with_an_unsubscribe_link_and_nowhere_to_post_is_automated() {
        let h = "From: Weekly <news@brand.example>\nList-Unsubscribe: <https://brand.example/u?x=1>, <mailto:u@brand.example>";
        assert_eq!(check(h, Some("news@brand.example")), Some(Automated::Newsletter));
        let notifications = "From: Service <notifications@service.example>\nList-Id: <repo.owner.service.example>\nList-Archive: <https://service.example/repo>";
        assert_eq!(check(notifications, Some("notifications@service.example")), Some(Automated::Newsletter));
        let posting_refused = "List-Id: <announce.example.org>\nList-Post: NO";
        assert_eq!(check(posting_refused, Some("announce@example.org")), Some(Automated::Newsletter));
    }

    #[test]
    fn a_discussion_list_is_people_and_is_left_alone() {
        let google_group = "From: Grace <grace@example.com>\nList-Id: <team.example.com>\nList-Post: <https://groups.example.com/g/team/post>, <mailto:team@example.com>\nList-Unsubscribe: <mailto:team+unsubscribe@example.com>\nPrecedence: list";
        assert_eq!(check(google_group, Some("grace@example.com")), None);
        let mailman = "List-Id: Friends <friends.lists.example.org>\nList-Post: <mailto:friends@lists.example.org>\nPrecedence: list";
        assert_eq!(check(mailman, Some("someone@example.org")), None);
    }

    #[test]
    fn precedence_junk_decides_and_bulk_and_list_do_not() {
        assert_eq!(check("Precedence: JUNK", Some("a@example.com")), Some(Automated::Bulk));
        assert_eq!(check("Precedence: auto_reply", Some("a@example.com")), Some(Automated::AutoReply));
        assert_eq!(check("Precedence: list", Some("a@example.com")), None);
        // A help desk marks every reply bulk, including the ones its staff
        // write; a newsletter marked bulk is caught by its unsubscribe link.
        assert_eq!(check("Precedence: bulk\nRT-Ticket: support.example #4411", Some("helpdesk@example.com")), None);
        assert_eq!(
            check("Precedence: bulk\nList-Unsubscribe: <https://brand.example/u>", Some("news@brand.example")),
            Some(Automated::Newsletter)
        );
        // ezmlm puts bulk on every post, and people post there.
        let ezmlm = "Precedence: bulk\nList-Id: <dev.project.example.org>\nList-Post: <mailto:dev@project.example.org>";
        assert_eq!(check(ezmlm, Some("committer@example.org")), None);
    }

    #[test]
    fn a_no_reply_sender_passing_on_a_person_is_left_alone() {
        let form = "Reply-To: Jane Visitor <jane@visitor.example>";
        assert_eq!(check(form, Some("no-reply@forms.example")), None);
        // A Reply-To that is the same no-reply address, or another one,
        // changes nothing.
        assert_eq!(
            check("Reply-To: no-reply@forms.example", Some("no-reply@forms.example")),
            Some(Automated::NoReplyAddress)
        );
        assert_eq!(
            check("Reply-To: <donotreply@bank.example>", Some("noreply@bank.example")),
            Some(Automated::NoReplyAddress)
        );
        // A relay on the service's own domain is the service answering.
        assert_eq!(
            check("Reply-To: Ada <d+AbC123@docs.example.com>", Some("comments-noreply@docs.example.com")),
            Some(Automated::NoReplyAddress)
        );
    }

    #[test]
    fn automatic_replies_are_recognized_and_auto_submitted_no_is_a_person() {
        assert_eq!(check("Auto-Submitted: auto-replied", Some("ada@example.com")), Some(Automated::AutoReply));
        assert_eq!(check("Auto-Submitted: auto-generated", Some("ada@example.com")), Some(Automated::AutoReply));
        assert_eq!(check("Auto-Submitted: auto-notified; owner-email=\"x@y\"", None), Some(Automated::AutoReply));
        assert_eq!(check("Auto-Submitted: no", Some("ada@example.com")), None);
        assert_eq!(check("Auto-Submitted: no (sent by a person)", Some("ada@example.com")), None);
        assert_eq!(check("Auto-Submitted: auto-forwarded", Some("ada@example.com")), None);
        assert_eq!(check("X-Autoreply: yes", Some("ada@example.com")), Some(Automated::AutoReply));
        assert_eq!(check("Return-Path: <>", Some("ada@example.com")), Some(Automated::AutoReply));
        assert_eq!(check("Return-Path: <ada@example.com>", Some("ada@example.com")), None);
    }

    #[test]
    fn delivery_reports_are_recognized() {
        let bounce = "Content-Type: multipart/report; report-type=delivery-status; boundary=x";
        assert_eq!(check(bounce, Some("mailer-daemon@mx.example")), Some(Automated::Report));
        let receipt = "Content-Type: Multipart/Report; report-type=disposition-notification; boundary=y";
        assert_eq!(check(receipt, Some("ada@example.com")), Some(Automated::Report));
    }

    #[test]
    fn no_reply_addresses_are_recognized_with_tags_prefixes_and_any_case() {
        for addr in [
            "noreply@example.com",
            "No-Reply@Example.com",
            "do-not-reply@bank.example",
            "donotreply+receipts@shop.example",
            "noreply-apps@example.com",
            "no-reply.billing@example.com",
            "MAILER-DAEMON@mx.example",
            "postmaster@example.org",
            "comments-noreply@docs.example.com",
            "messages-noreply@social.example",
            "billing.no-reply@example.com",
        ] {
            assert_eq!(check("", Some(addr)), Some(Automated::NoReplyAddress), "{addr}");
        }
        for addr in [
            "noreplying@example.com",
            "reply@example.com",
            "noreen@example.com",
            "not-an-address",
            "snoreply@example.com",
        ] {
            assert_eq!(check("", Some(addr)), None, "{addr}");
        }
        assert_eq!(check("", None), None);
    }

    #[test]
    fn the_stored_names_are_stable() {
        // These strings are persisted on messages; changing one orphans the
        // messages already stored under it.
        let names: Vec<&str> = [
            Automated::Report,
            Automated::AutoReply,
            Automated::Bulk,
            Automated::NoReplyAddress,
            Automated::Newsletter,
        ]
        .iter()
        .map(|a| a.as_str())
        .collect();
        assert_eq!(names, ["report", "auto_reply", "bulk", "no_reply_address", "newsletter"]);
    }
}
