#!/usr/bin/env node
/**
 * Single source of version truth: root package.json "version".
 *
 *   node scripts/sync-version.mjs          # write the root version everywhere
 *   node scripts/sync-version.mjs --check  # exit 1 if anything disagrees
 *   node scripts/sync-version.mjs 0.2.0    # set a new version, then sync
 *
 * Kept in sync: apps/desktop/package.json, packages/*\/package.json,
 * apps/desktop/src-tauri/tauri.conf.json, Cargo.toml [workspace.package],
 * engine/pyproject.toml + engine/src/mimic_engine/__init__.py (PEP 440 form),
 * CHANGELOG heading check.
 */
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const args = process.argv.slice(2);
const check = args.includes("--check");
const explicit = args.find((a) => /^\d+\.\d+\.\d+(-[0-9A-Za-z.]+)?$/.test(a));

const rootPkgPath = resolve(root, "package.json");
const rootPkg = JSON.parse(readFileSync(rootPkgPath, "utf8"));
if (explicit && !check) {
  rootPkg.version = explicit;
  writeFileSync(rootPkgPath, JSON.stringify(rootPkg, null, 2) + "\n");
}
const version = rootPkg.version;
const semver = /^(\d+)\.(\d+)\.(\d+)(?:-([0-9A-Za-z.]+))?$/.exec(version);
if (!semver) {
  console.error(`root version "${version}" is not semver`);
  process.exit(1);
}
const [, major, minor, patch, pre] = semver;

/** PEP 440: 0.1.0-alpha.1 → 0.1.0a1, -beta.2 → 0.1.0b2, -rc.1 → 0.1.0rc1 */
function pep440(v) {
  if (!pre) return `${major}.${minor}.${patch}`;
  const m = /^(alpha|beta|rc)\.?(\d+)?$/.exec(pre);
  if (!m)
    throw new Error(
      `pre-release "${pre}" cannot be expressed in PEP 440 (use alpha.N, beta.N or rc.N)`,
    );
  const tag = m[1] === "alpha" ? "a" : m[1] === "beta" ? "b" : "rc";
  return `${major}.${minor}.${patch}${tag}${m[2] ?? "0"}`;
}

const problems = [];
let changed = 0;

function editFile(rel, transform, label = rel) {
  const path = resolve(root, rel);
  if (!existsSync(path)) {
    problems.push(`${label}: file missing`);
    return;
  }
  const before = readFileSync(path, "utf8");
  const after = transform(before);
  if (after === null) {
    problems.push(`${label}: pattern not found`);
    return;
  }
  if (after !== before) {
    if (check) problems.push(`${label}: out of sync`);
    else {
      writeFileSync(path, after);
      changed++;
    }
  }
}

function jsonVersion(rel) {
  editFile(rel, (text) => {
    const obj = JSON.parse(text);
    if (obj.version === version) return text;
    obj.version = version;
    return JSON.stringify(obj, null, 2) + "\n";
  });
}

jsonVersion("apps/desktop/package.json");
jsonVersion("packages/contracts/package.json");
jsonVersion("packages/ui/package.json");
jsonVersion("packages/test-fixtures/package.json");
jsonVersion("apps/desktop/src-tauri/tauri.conf.json");

editFile("Cargo.toml", (t) => {
  const re = /(\[workspace\.package\][\s\S]*?\nversion = ")([^"]+)(")/;
  return re.test(t) ? t.replace(re, `$1${version}$3`) : null;
});
editFile("engine/pyproject.toml", (t) => {
  const re = /(\[project\][\s\S]*?\nversion = ")([^"]+)(")/;
  return re.test(t) ? t.replace(re, `$1${pep440(version)}$3`) : null;
});
editFile("engine/src/mimic_engine/__init__.py", (t) => {
  const re = /(__version__ = ")([^"]+)(")/;
  return re.test(t) ? t.replace(re, `$1${pep440(version)}$3`) : null;
});
editFile("crates/mimic-core/src/version.rs", (t) => {
  // APP_VERSION comes from Cargo; ANALYSIS_VERSION is a policy value that
  // changes only when the voice metrics change. Neither is synced here — this
  // entry exists so a missing file is caught.
  return t;
});

// CHANGELOG must have a heading for this version.
const changelog = readFileSync(resolve(root, "CHANGELOG.md"), "utf8");
if (!changelog.includes(`## [${version}]`))
  problems.push(`CHANGELOG.md: no "## [${version}]" section`);

// Cargo.lock must agree (it is regenerated by cargo; we only check).
const lock = readFileSync(resolve(root, "Cargo.lock"), "utf8");
for (const crate of ["mimic-core", "mimic-keychain", "mimic-desktop"]) {
  const re = new RegExp(`name = "${crate}"\\nversion = "([^"]+)"`);
  const m = re.exec(lock);
  if (!m) problems.push(`Cargo.lock: ${crate} missing`);
  else if (m[1] !== version) problems.push(`Cargo.lock: ${crate} is ${m[1]} (run cargo update -w)`);
}

if (problems.length) {
  console.error(`version ${version}: ${problems.length} problem(s)`);
  for (const p of problems) console.error(`  - ${p}`);
  process.exit(1);
}
console.log(
  check
    ? `version ${version} is consistent everywhere`
    : `version ${version} synced (${changed} file(s) changed)`,
);
